# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13 for x64
      uses: actions/setup-java@v2
      with:
        java-version: '13'
        distribution: 'adopt'
        architecture: x64
    - name: Build with Maven
      run: mvn -B package --file pom.xml
